version: '3.8'

services:
  # Backend Flask
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: autobiz-backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///database.db
    depends_on:
      - redis
    networks:
      - autobiz-network

  # Frontend Static Server
  frontend:
    image: nginx:alpine
    container_name: autobiz-frontend
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - autobiz-network

  # Redis para cache e rate limiting
  redis:
    image: redis:alpine
    container_name: autobiz-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - autobiz-network

volumes:
  redis-data:

networks:
  autobiz-network:
    driver: bridge